Bump to mongoose version 4.4 to avoid error
Error visible in command line is:

{ [Error: Cannot find module '../build/Release/bson'] code:
'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version